### ISSUE TITLE
Unexpected expression to be null with semi-colon

### ISSUE THREAD

**Issue by cloudrex** [IonLanguage/Ion#21]
A parser is still having problems with semi-colons after function calls. Reproduce with the information below. However, the error does not occur when the semi-colon is omitted.

Input:
```rust
int main()
{
    printf();

    return 0; 
}
```

Error:
```shell
Unhandled Exception: System.Exception: Unexpected expression to be null
   at Ion.Parsing.BlockParser.Parse(TokenStream stream) in /home/atlas/workspace/Ion/Ion/Parsing/BlockParser.cs:line 69
   at Ion.Parsing.FunctionParser.Parse(TokenStream stream) in /home/atlas/workspace/Ion/Ion/Parsing/FunctionParser.cs:line 20
   at Ion.Parsing.Driver.Next() in /home/atlas/workspace/Ion/Ion/Parsing/Driver.cs:line 70
```

**Comment by Draem** [comment]
This was a really dumb mistake on my part which is now fixed in [this commit](https://github.com/IonLanguage/Ion/commit/6a4fe04b82e3049655813ef4f4e246249004202d)
