### ISSUE TITLE
Last item being interpreted as EOF in Stream

### ISSUE THREAD

**Issue by cloudrex** [IonLanguage/Ion#33]
The last item is being interpreted as the EOF (end-of-file) item. This occurs, for example, when solely declaring a struct in a module. This should be fixed once #19 is implemented.

Exception trace:
```
Starting test execution, please wait...
Failed   Struct
Error Message:
 System.IndexOutOfRangeException : Expected 'SymbolBlockR' to be encountered, but got EOF
Stack Trace:
   at Ion.SyntaxAnalysis.TokenStream.NextUntil(TokenType type, NextUntilCallback callback) in D:\apps\Ion\Ion\SyntaxAnalysis\TokenStream.cs:line 172
   at Ion.Parsing.StructDefParser.Parse(ParserContext context) in D:\apps\Ion\Ion\Parsing\Struct\Definition\StructDefParser.cs:line 31
   at Ion.Parsing.TopLevelHandler.Invoke(ParserContext context) in D:\apps\Ion\Ion\Parsing\TopLevelParser.cs:line 67
   at Ion.Parsing.Driver.Next() in D:\apps\Ion\Ion\Parsing\Driver\Driver.cs:line 91
   at Ion.Tests.Core.ConstructWrapper.InvokeDriver(Int32 times) in D:\apps\Ion\Ion.Tests\Wrappers\ConstructWrapper.cs:line 65
   at Ion.Tests.CodeGeneration.StructTests.Struct() in D:\apps\Ion\Ion.Tests\CodeGeneration\StructTests.cs:line 16
```

**Comment by cloudrex** [comment]
After further research, upon placing a method inside the module to avoid this exception, I've discovered and fixed a bug with the `StructDefParser` double-skipping tokens. Now the exception is no longer present somehow.
